/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package OddJava;

public class App {
    public String getPatient() {
        return "Hello patient.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getPatient());
    }
}
